import { CollapsibleCodeBlock } from '@site/src/components/collapsible-code-block';
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import { FileTreeInfo } from '@site/src/components/file-tree-info';

export const FileTree = () => (
  <FileTreeInfo>
    <CollapsibleCodeBlock language="log" title="File Tree">
      {`.
// highlight-modified
├── build.gradle  # or build.gradle.kts in kotlin
├── ...           # other root files omitted
└── src
    ├── main
    │   ├── ...   # source code omitted
    │   └── resources
    │       ├── application-dev.yaml
    │       ├── application.yaml
// highlight-added-start
    │       ├── hibernate.reveng.xml
    │       ├── hibernate-tools.properties
// highlight-added-end
    │       ├── logback-spring.xml
    │       ├── openapi.yaml
// highlight-added-start
    │       ├── sakila-data.sql
    │       ├── sakila-schema.sql
    │       └── templates/hibernate/pojo/Pojo.ftl
// highlight-added-end
    └── test/...    # test sources omitted`}
    </CollapsibleCodeBlock>
  </FileTreeInfo>
);

export const HibernateRevengXml = () => (
  <CollapsibleCodeBlock language="xml" title="resources/hibernate.reveng.xml">
    {`// highlight-added-start
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hibernate-reverse-engineering PUBLIC
        "-//Hibernate/Hibernate Reverse Engineering DTD 3.0//EN"
        "http://hibernate.org/dtd/hibernate-reverse-engineering-3.0.dtd" >

<hibernate-reverse-engineering>
    <type-mapping>
        <sql-type jdbc-type="TINYINT" hibernate-type="java.lang.Integer"/>
        <sql-type jdbc-type="SMALLINT" hibernate-type="java.lang.Integer"/>
        <sql-type jdbc-type="BIT" hibernate-type="java.lang.Boolean" />
        <sql-type jdbc-type="TIMESTAMP" hibernate-type="java.time.LocalDateTime" />
        <sql-type jdbc-type="DATE" hibernate-type="java.time.LocalDate" />
    </type-mapping>

    <table-filter match-schema="PUBLIC" match-name=".*" />
</hibernate-reverse-engineering>
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

export const HibernateToolsProperties = () => (
  <CollapsibleCodeBlock
    language="properties"
    title="resources/hibernate-tools.properties"
  >
    {`// highlight-added-start
hibernate.connection.driver_class=org.h2.Driver
hibernate.connection.username=sa
hibernate.connection.password=
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.connection.provider_class=org.hibernate.connection.DriverManagerConnectionProvider
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

const HibernatePojoJava = () => (
  <CollapsibleCodeBlock
    language="ftl"
    title="resources/templates/hibernate/pojo/Pojo.ftl"
  >
    {`// highlight-added-start
<#-- Hibernate Tools 6.x Compatible Template -->
<#-- Available objects: pojo, clazz -->
\${pojo.getPackageDeclaration()}

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

<#-- Determine if this is a composite key class (Embeddable) -->
<#assign className = pojo.getDeclarationName()>
<#assign isCompositeKey = !pojo.hasIdentifierProperty() && className?ends_with("Id")>

<#-- For entities: check if they use a composite key -->
<#assign usesCompositeKey = false>
<#assign compositeKeyTypeName = "">
<#assign compositeKeyFields = []>
<#if !isCompositeKey>
<#list pojo.getAllPropertiesIterator() as property>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#if property.name == "id" && javaType?ends_with("Id")>
        <#assign usesCompositeKey = true>
        <#assign compositeKeyTypeName = javaType>
    </#if>
</#list>
</#if>

/**
 * \${className} generated by Hibernate Tools
 */
<#if isCompositeKey>
@Embeddable
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode
public class \${className} implements Serializable {
<#else>
@Entity
@Table(name = "\${clazz.table.name}"<#if clazz.table.schema?? && clazz.table.schema?has_content>, schema = "\${clazz.table.schema}"</#if>)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class \${className} implements Serializable {
</#if>

    @Serial
    private static final long serialVersionUID = 1L;

<#-- Iterate over all properties -->
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign valueTypeName = property.value.class.simpleName>

    <#-- Check if this is the identifier -->
    <#assign isId = pojo.hasIdentifierProperty() && pojo.getIdentifierProperty().name == propertyName>

    <#-- Check if this is a composite/embedded id -->
    <#assign isEmbeddedId = propertyName == "id" && javaType?ends_with("Id")>

<#if isCompositeKey>
    <#-- For composite key classes, just generate columns without @Id -->
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    private \${javaType} \${propertyName};

<#else>
    <#-- Regular entity logic -->

    <#-- Handle EmbeddedId (composite primary key reference) -->
    <#if isEmbeddedId>
    @EmbeddedId
    private \${javaType} \${propertyName};

    <#-- Generate @Id annotation for simple primary key -->
    <#elseif isId>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}")
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}")
    </#if>
    </#if>
    private \${javaType} \${propertyName};

    <#-- Handle ManyToOne relationships -->
    <#elseif valueTypeName == "ManyToOne">
    @ManyToOne(fetch = FetchType.LAZY)
    <#-- Determine column name for potential @MapsId -->
    <#assign columnName = "">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    <#assign columnName = column.name>
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    <#assign columnName = column.name>
    </#if>
    </#if>
    <#-- If entity uses composite key, add @MapsId -->
    <#if usesCompositeKey && columnName?has_content>
    <#-- Convert ACTOR_ID -> actorId for @MapsId value -->
    <#assign mapsIdValue = columnName?lower_case?replace("_", " ")?capitalize?replace(" ", "")?uncap_first>
    @MapsId("\${mapsIdValue}")
    </#if>
    <#if columnName?has_content>
    @JoinColumn(name = "\${columnName}")
    </#if>
    private \${javaType} \${propertyName};

    <#-- Handle OneToMany relationships (Set, Bag, List) -->
    <#elseif valueTypeName == "Set" || valueTypeName == "Bag" || valueTypeName == "List">
    <#--
      Derive mappedBy value from property name pattern.
      Property naming pattern: {targetEntity}For{ColumnSuffix} (e.g., filmsForLanguageId)
      Inverse property pattern: {thisEntity}By{ColumnSuffix} (e.g., languageByLanguageId)
    -->
    <#assign mappedByValue = className?uncap_first>
    <#if propertyName?contains("For")>
        <#assign forIndex = propertyName?index_of("For")>
        <#if (forIndex > 0) && (forIndex < propertyName?length - 3)>
            <#assign columnSuffix = propertyName?substring(forIndex + 3)>
            <#assign mappedByValue = className?uncap_first + "By" + columnSuffix>
        </#if>
    </#if>
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "\${mappedByValue}")
    @Builder.Default
    private \${javaType} \${propertyName} = new HashSet<>(0);

    <#-- Handle regular columns (BasicValue, SimpleValue) -->
    <#elseif valueTypeName == "BasicValue" || valueTypeName == "SimpleValue">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if><#if (column.length)?? && column.length != 255 && javaType == "String">, length = \${column.length?c}</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    private \${javaType} \${propertyName};

    <#-- Handle Component/Embedded types -->
    <#elseif valueTypeName == "Component">
    @Embedded
    private \${javaType} \${propertyName};

    <#-- Fallback for unknown types -->
    <#else>
    // TODO: Unknown mapping type "\${valueTypeName}" for property "\${propertyName}"
    private \${javaType} \${propertyName};

    </#if>
</#if>
</#list>
}
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

const HibernatePojoKt = () => (
  <CollapsibleCodeBlock
    language="ftl"
    title="resources/templates/hibernate/pojo/Pojo.ftl"
  >
    {`// highlight-added-start
<#-- Hibernate Tools 6.x Compatible Template for Kotlin -->
<#-- Available objects: pojo, clazz -->
\${pojo.getPackageDeclaration()}

import jakarta.persistence.*
import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalDateTime

<#-- Determine if this is a composite key class (Embeddable) -->
<#assign className = pojo.getDeclarationName()>
<#assign isCompositeKey = !pojo.hasIdentifierProperty() && className?ends_with("Id")>

<#-- For entities: check if they use a composite key -->
<#assign usesCompositeKey = false>
<#assign compositeKeyTypeName = "">
<#if !isCompositeKey>
<#list pojo.getAllPropertiesIterator() as property>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#if property.name == "id" && javaType?ends_with("Id")>
        <#assign usesCompositeKey = true>
        <#assign compositeKeyTypeName = javaType>
    </#if>
</#list>
</#if>

<#-- Helper function to convert Java types to Kotlin types -->
<#function toKotlinType javaType>
    <#if javaType == "int" || javaType == "Integer" || javaType == "java.lang.Integer">
        <#return "Int">
    <#elseif javaType == "long" || javaType == "Long" || javaType == "java.lang.Long">
        <#return "Long">
    <#elseif javaType == "short" || javaType == "Short" || javaType == "java.lang.Short">
        <#return "Short">
    <#elseif javaType == "byte" || javaType == "Byte" || javaType == "java.lang.Byte">
        <#return "Byte">
    <#elseif javaType == "double" || javaType == "Double" || javaType == "java.lang.Double">
        <#return "Double">
    <#elseif javaType == "float" || javaType == "Float" || javaType == "java.lang.Float">
        <#return "Float">
    <#elseif javaType == "boolean" || javaType == "Boolean" || javaType == "java.lang.Boolean">
        <#return "Boolean">
    <#elseif javaType == "char" || javaType == "Character" || javaType == "java.lang.Character">
        <#return "Char">
    <#elseif javaType == "String" || javaType == "java.lang.String">
        <#return "String">
    <#elseif javaType == "BigDecimal" || javaType == "java.math.BigDecimal">
        <#return "BigDecimal">
    <#elseif javaType == "LocalDate" || javaType == "java.time.LocalDate">
        <#return "LocalDate">
    <#elseif javaType == "LocalDateTime" || javaType == "java.time.LocalDateTime">
        <#return "LocalDateTime">
    <#elseif javaType == "byte[]" || javaType == "Byte[]">
        <#return "ByteArray">
    <#elseif javaType == "int[]" || javaType == "Integer[]">
        <#return "IntArray">
    <#elseif javaType == "long[]" || javaType == "Long[]">
        <#return "LongArray">
    <#elseif javaType == "short[]" || javaType == "Short[]">
        <#return "ShortArray">
    <#elseif javaType == "double[]" || javaType == "Double[]">
        <#return "DoubleArray">
    <#elseif javaType == "float[]" || javaType == "Float[]">
        <#return "FloatArray">
    <#elseif javaType == "boolean[]" || javaType == "Boolean[]">
        <#return "BooleanArray">
    <#elseif javaType == "char[]" || javaType == "Character[]">
        <#return "CharArray">
    <#elseif javaType?starts_with("Set<")>
        <#return "MutableSet<" + javaType?substring(4)>
    <#elseif javaType?starts_with("java.util.Set<")>
        <#return "MutableSet<" + javaType?substring(14)>
    <#else>
        <#return javaType>
    </#if>
</#function>

/**
 * \${className} generated by Hibernate Tools
 */
<#if isCompositeKey>
@Embeddable
data class \${className}(
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign kotlinType = toKotlinType(javaType)>
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
</#list>
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L
    }
}
<#else>
@Entity
@Table(name = "\${clazz.table.name}"<#if clazz.table.schema?? && clazz.table.schema?has_content>, schema = "\${clazz.table.schema}"</#if>)
class \${className}(
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign kotlinType = toKotlinType(javaType)>
    <#assign valueTypeName = property.value.class.simpleName>
    <#assign isId = pojo.hasIdentifierProperty() && pojo.getIdentifierProperty().name == propertyName>
    <#assign isEmbeddedId = propertyName == "id" && javaType?ends_with("Id")>

    <#if isEmbeddedId>
    @EmbeddedId
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif isId>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}")
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}")
    </#if>
    </#if>
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "ManyToOne">
    @ManyToOne(fetch = FetchType.LAZY)
    <#assign columnName = "">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    <#assign columnName = column.name>
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    <#assign columnName = column.name>
    </#if>
    </#if>
    <#if usesCompositeKey && columnName?has_content>
    <#assign mapsIdValue = columnName?lower_case?replace("_", " ")?capitalize?replace(" ", "")?uncap_first>
    @MapsId("\${mapsIdValue}")
    </#if>
    <#if columnName?has_content>
    @JoinColumn(name = "\${columnName}")
    </#if>
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "Set" || valueTypeName == "Bag" || valueTypeName == "List">
    <#assign mappedByValue = className?uncap_first>
    <#if propertyName?contains("For")>
        <#assign forIndex = propertyName?index_of("For")>
        <#if (forIndex > 0) && (forIndex < propertyName?length - 3)>
            <#assign columnSuffix = propertyName?substring(forIndex + 3)>
            <#assign mappedByValue = className?uncap_first + "By" + columnSuffix>
        </#if>
    </#if>
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "\${mappedByValue}")
    var \${propertyName}: \${kotlinType} = mutableSetOf()<#if property_has_next>,</#if>
    <#elseif valueTypeName == "BasicValue" || valueTypeName == "SimpleValue">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if><#if (column.length)?? && column.length != 255 && (kotlinType == "String")>, length = \${column.length?c}</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    <#elseif valueTypeName == "Component">
    @Embedded
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    <#else>
    // TODO: Unknown mapping type "\${valueTypeName}" for property "\${propertyName}"
    var \${propertyName}: \${kotlinType}? = null<#if property_has_next>,</#if>
    </#if>
</#list>
) : Serializable {
    companion object {
        private const val serialVersionUID = 1L
    }
}
</#if>
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

const HibernatePojoGroovy = () => (
  <CollapsibleCodeBlock
    language="ftl"
    title="resources/templates/hibernate/pojo/Pojo.ftl"
  >
    {`// highlight-added-start
<#-- Hibernate Tools 6.x Compatible Template for Groovy -->
<#-- Note: This must be in templates/hibernate/pojo/Pojo.ftl -->
\${pojo.getPackageDeclaration()}

import groovy.transform.CompileStatic
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString
import groovy.transform.builder.Builder
import groovy.transform.builder.SimpleStrategy
import jakarta.persistence.*

import java.math.BigDecimal
import java.time.LocalDate
import java.time.LocalDateTime

<#-- Determine if this is a composite key class (Embeddable) -->
<#assign className = pojo.getDeclarationName()>
<#assign isCompositeKey = !pojo.hasIdentifierProperty() && className?ends_with("Id")>

<#-- For entities: check if they use a composite key -->
<#assign usesCompositeKey = false>
<#assign compositeKeyTypeName = "">
<#if !isCompositeKey>
<#list pojo.getAllPropertiesIterator() as property>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#if property.name == "id" && javaType?ends_with("Id")>
        <#assign usesCompositeKey = true>
        <#assign compositeKeyTypeName = javaType>
    </#if>
</#list>
</#if>

/**
 * \${className} generated by Hibernate Tools
 */
<#if isCompositeKey>
@CompileStatic
@Embeddable
@Builder(builderStrategy = SimpleStrategy, prefix = '')
@EqualsAndHashCode
@ToString(includePackage = false)
class \${className} implements Serializable {
<#else>
@CompileStatic
@Entity
@Table(name = "\${clazz.table.name}"<#if clazz.table.schema?? && clazz.table.schema?has_content>, schema = "\${clazz.table.schema}"</#if>)
@Builder(builderStrategy = SimpleStrategy, prefix = '')
@ToString(includePackage = false, includeNames = true)
class \${className} implements Serializable {
</#if>

    private static final long serialVersionUID = 1L

<#-- Iterate over all properties -->
<#list pojo.getAllPropertiesIterator() as property>
    <#assign propertyName = property.name>
    <#assign javaType = pojo.getJavaTypeName(property, true)>
    <#assign valueTypeName = property.value.class.simpleName>

    <#-- Check if this is the identifier -->
    <#assign isId = pojo.hasIdentifierProperty() && pojo.getIdentifierProperty().name == propertyName>

    <#-- Check if this is a composite/embedded id -->
    <#assign isEmbeddedId = propertyName == "id" && javaType?ends_with("Id")>

<#if isCompositeKey>
    <#-- For composite key classes, just generate columns without @Id -->
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    \${javaType} \${propertyName}

<#else>
    <#-- Regular entity logic -->

    <#-- Handle EmbeddedId (composite primary key reference) -->
    <#if isEmbeddedId>
    @EmbeddedId
    \${javaType} \${propertyName}

    <#-- Generate @Id annotation for simple primary key -->
    <#elseif isId>
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}")
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}")
    </#if>
    </#if>
    \${javaType} \${propertyName}

    <#-- Handle ManyToOne relationships -->
    <#elseif valueTypeName == "ManyToOne">
    @ManyToOne(fetch = FetchType.LAZY)
    <#-- Determine column name for potential @MapsId -->
    <#assign columnName = "">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    <#assign columnName = column.name>
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    <#assign columnName = column.name>
    </#if>
    </#if>
    <#-- If entity uses composite key, add @MapsId -->
    <#if usesCompositeKey && columnName?has_content>
    <#-- Convert ACTOR_ID -> actorId for @MapsId value -->
    <#assign mapsIdValue = columnName?lower_case?replace("_", " ")?capitalize?replace(" ", "")?uncap_first>
    @MapsId("\${mapsIdValue}")
    </#if>
    <#if columnName?has_content>
    @JoinColumn(name = "\${columnName}")
    </#if>
    \${javaType} \${propertyName}

    <#-- Handle OneToMany relationships (Set, Bag, List) -->
    <#elseif valueTypeName == "Set" || valueTypeName == "Bag" || valueTypeName == "List">
    <#assign mappedByValue = className?uncap_first>
    <#if propertyName?contains("For")>
        <#assign forIndex = propertyName?index_of("For")>
        <#if (forIndex > 0) && (forIndex < propertyName?length - 3)>
            <#assign columnSuffix = propertyName?substring(forIndex + 3)>
            <#assign mappedByValue = className?uncap_first + "By" + columnSuffix>
        </#if>
    </#if>
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "\${mappedByValue}")
    Set<\${javaType?replace("Set<", "")?replace(">", "")}> \${propertyName} = new HashSet<>(0)

    <#-- Handle regular columns (BasicValue, SimpleValue) -->
    <#elseif valueTypeName == "BasicValue" || valueTypeName == "SimpleValue">
    <#if (property.value.columns)?? && property.value.columns?has_content>
    <#list property.value.columns as column>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if><#if (column.length)?? && column.length != 255 && javaType == "String">, length = \${column.length?c}</#if>)
    <#break>
    </#list>
    <#elseif (property.value.columnIterator)??>
    <#assign columnIterator = property.value.columnIterator>
    <#if columnIterator.hasNext()>
    <#assign column = columnIterator.next()>
    @Column(name = "\${column.name}"<#if !column.nullable>, nullable = false</#if>)
    </#if>
    </#if>
    \${javaType} \${propertyName}

    <#-- Handle Component/Embedded types -->
    <#elseif valueTypeName == "Component">
    @Embedded
    \${javaType} \${propertyName}

    <#-- Fallback for unknown types -->
    <#else>
    // TODO: Unknown mapping type "\${valueTypeName}" for property "\${propertyName}"
    \${javaType} \${propertyName}

    </#if>
</#if>
</#list>
}
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

export const HibernatePojo = () => (
  <Tabs groupId="language" queryString>
    <TabItem value="java" label="Java" default>
      <HibernatePojoJava />
    </TabItem>
    <TabItem value="kotlin" label="Kotlin">
      <HibernatePojoKt />
    </TabItem>
    <TabItem value="groovy" label="Groovy">
      <HibernatePojoGroovy />
    </TabItem>
  </Tabs>
);

const BuildGradleJava = () => (
  <CollapsibleCodeBlock language="groovy" title="build.gradle">
    {`// ...
configurations {
  // ...
// highlight-added
  hibernateTools
}
// ...
dependencies {
  // ...
// highlight-added-start
  def h2Version = '2.4.240'
  def hibernateVersion = '7.0.2.Final'
  hibernateTools "com.h2database:h2:\${h2Version}"
  hibernateTools "org.hibernate.tool:hibernate-tools-ant:\${hibernateVersion}"
  hibernateTools "org.hibernate.orm:hibernate-core:\${hibernateVersion}"

  developmentOnly "com.h2database:h2:\${h2Version}"
  testRuntimeOnly "com.h2database:h2:\${h2Version}"
  developmentOnly 'org.springframework.boot:spring-boot-h2console'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
// highlight-added-end
}
// ...
// highlight-added-start
tasks.register('generateEntities') {
  group = 'build'
  description = 'Reverse engineers resources/sakila-schema.sql into JPA Entities'

  def outputDir = layout.buildDirectory.dir("generated/sources/hibernate")
  def sqlFile = layout.projectDirectory.file("src/main/resources/sakila-schema.sql")
  def revengFile = layout.projectDirectory.file("src/main/resources/hibernate.reveng.xml")
  def basePropsFile = layout.projectDirectory.file("src/main/resources/hibernate-tools.properties")
  def templateDir = layout.projectDirectory.dir("src/main/resources/templates/hibernate")

  inputs.file(sqlFile)
  inputs.file(revengFile)
  inputs.file(basePropsFile).optional()
  inputs.dir(templateDir).optional()
  outputs.dir(outputDir)

  doLast {
    def tempPropsFile = layout.buildDirectory.file("tmp/hibernate-tools.properties").get().asFile
    tempPropsFile.parentFile.mkdirs()

    def props = new Properties()
    if (basePropsFile.asFile.exists()) {
      basePropsFile.asFile.withInputStream { props.load(it) }
    }
    props.setProperty(
        'hibernate.connection.url',
        "jdbc:h2:mem:sakila;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM '\${sqlFile.asFile.absolutePath.replace('\\', '/')}'"
        )

    tempPropsFile.withOutputStream { props.store(it, null) }

    def destDir = outputDir.get().asFile
    destDir.mkdirs()

    ant.taskdef(
        name: 'hibernatetool',
        classname: 'org.hibernate.tool.ant.HibernateToolTask',
        classpath: configurations.hibernateTools.asPath
        )

    ant.hibernatetool(
        destdir: destDir,
        templatepath: templateDir.asFile
        ) {
          jdbcconfiguration(
              propertyfile: tempPropsFile,
              revengfile: revengFile.asFile,
              packagename: "$\{project.group}.\${project.name}.generated.entity",
              detectmanytomany: true,
              detectoptimisticlock: true
              )

          hbm2java(jdk5: true, ejb3: true)
        }
  }
}
// highlight-added-end

sourceSets {
  main {
    java {
      // ...
// highlight-added
      srcDir(layout.buildDirectory.dir("generated/sources/hibernate"))
    }
  }
}

tasks.named('compileJava') {
  // ...
// highlight-added
  dependsOn 'generateEntities'
}
// ...`}
  </CollapsibleCodeBlock>
);

const BuildGradleKt = () => (
  <CollapsibleCodeBlock language="kts" title="build.gradle.kts">
    {`// highlight-added
import java.util.Properties

plugins {
  // ...
// highlight-added
  kotlin("plugin.jpa") version "2.2.21"
}
// ...
// highlight-added
val hibernateTools: Configuration by configurations.creating
// ...
dependencies {
  // ...
// highlight-added-start
  val hibernateVersion = "7.0.2.Final"
  val h2Version = "2.4.240"
  hibernateTools("com.h2database:h2:$h2Version")
  hibernateTools("org.hibernate.tool:hibernate-tools-ant:$hibernateVersion")
  hibernateTools("org.hibernate.orm:hibernate-core:$hibernateVersion")

  developmentOnly("com.h2database:h2:$h2Version")
  testRuntimeOnly("com.h2database:h2:$h2Version")
  developmentOnly("org.springframework.boot:spring-boot-h2console")
  implementation("org.springframework.boot:spring-boot-starter-data-jpa")
  testImplementation("org.springframework.boot:spring-boot-starter-data-jpa-test")
// highlight-added-end
}
// ...
// highlight-added
val hibernateGeneratedSourcesDir = layout.buildDirectory.dir("generated/sources/hibernate")
// ...
// highlight-added-start
tasks.register("generateEntities") {
  group = "build"
  description = "Reverse engineers resources/sakila.sql into JPA Entities (Kotlin)"

  val sqlFile = file("src/main/resources/sakila-schema.sql")
  val revengFile = file("src/main/resources/hibernate.reveng.xml")
  val basePropsFile = file("src/main/resources/hibernate-tools.properties")
  val templateDir = file("src/main/resources/templates/hibernate")

  inputs.file(sqlFile)
  inputs.file(revengFile)
  inputs.file(basePropsFile).optional()
  inputs.dir(templateDir).optional()
  outputs.dir(hibernateGeneratedSourcesDir)

  doLast {
    val tempPropsFile = layout.buildDirectory.file("tmp/hibernate-tools.properties").get().asFile
    tempPropsFile.parentFile.mkdirs()

    val props = Properties()
    if (basePropsFile.exists()) {
      basePropsFile.inputStream().use { stream -> props.load(stream) }
    }

    val sakilaSqlPath = sqlFile.absolutePath.replace("\\\\", "/")
    props.setProperty(
        "hibernate.connection.url",
        "jdbc:h2:mem:sakila;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM '$sakilaSqlPath'",
    )

    tempPropsFile.outputStream().use { stream -> props.store(stream, null) }

    val destDir = hibernateGeneratedSourcesDir.get().asFile
    destDir.mkdirs()

    ant.withGroovyBuilder {
      "taskdef"(
          "name" to "hibernatetool",
          "classname" to "org.hibernate.tool.ant.HibernateToolTask",
          "classpath" to hibernateTools.asPath,
      )

      "hibernatetool"(
          "destdir" to destDir,
          "templatepath" to templateDir,
      ) {
        "jdbcconfiguration"(
            "propertyfile" to tempPropsFile,
            "revengfile" to revengFile,
            "packagename" to "\${project.group}.\${project.name}.generated.entity",
            "detectmanytomany" to true,
            "detectoptimisticlock" to true,
        )
        "hbm2java"("jdk5" to true, "ejb3" to true)
      }
    }

    val entityDir =
        File(destDir, "\${project.group}.\${project.name}.generated.entity".replace('.', '/'))
    entityDir
        .listFiles()
        ?.filter { it.extension == "java" }
        ?.forEach { javaFile ->
          val ktFile = File(javaFile.parentFile, "\${javaFile.nameWithoutExtension}.kt")
          javaFile.renameTo(ktFile)
          println("Renamed: \${javaFile.name} -> \${ktFile.name}")
        }
  }
}
// highlight-added-end

kotlin.sourceSets["main"].kotlin {
  // ...
// highlight-added
  srcDir(hibernateGeneratedSourcesDir)
}

tasks.named("compileKotlin") {
  // ...
// highlight-added
  dependsOn("generateEntities")
}

tasks.withType<org.jetbrains.kotlin.gradle.internal.KaptGenerateStubsTask> {
  // ...
// highlight-added
  dependsOn("generateEntities")
}
// ...`}
  </CollapsibleCodeBlock>
);

const BuildGradleGroovy = () => (
  <CollapsibleCodeBlock language="groovy" title="build.gradle">
    {`// ...
configurations {
  // ...
// highlight-added
  hibernateTools
}
// ...
dependencies {
  // ...
// highlight-added-start
  def h2Version = '2.4.240'
  def hibernateVersion = '7.0.2.Final'
  hibernateTools "com.h2database:h2:\${h2Version}"
  hibernateTools "org.hibernate.tool:hibernate-tools-ant:\${hibernateVersion}"
  hibernateTools "org.hibernate.orm:hibernate-core:\${hibernateVersion}"

  developmentOnly "com.h2database:h2:\${h2Version}"
  testRuntimeOnly "com.h2database:h2:\${h2Version}"
  developmentOnly 'org.springframework.boot:spring-boot-h2console'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
// highlight-added-end
}
// ...
// highlight-added-start
tasks.register('generateEntities') {
  group = 'build'
  description = 'Reverse engineers resources/sakila.sql into Groovy JPA Entities'

  def outputDir = layout.buildDirectory.dir("generated/sources/hibernate")
  def sqlFile = layout.projectDirectory.file("src/main/resources/sakila-schema.sql")
  def revengFile = layout.projectDirectory.file("src/main/resources/hibernate.reveng.xml")
  def basePropsFile = layout.projectDirectory.file("src/main/resources/hibernate-tools.properties")
  def templateDir = layout.projectDirectory.dir("src/main/resources/templates/hibernate")

  inputs.file(sqlFile)
  inputs.file(revengFile)
  inputs.file(basePropsFile).optional()
  inputs.dir(templateDir).optional()
  outputs.dir(outputDir)

  doLast {
    def tempPropsFile = layout.buildDirectory.file("tmp/hibernate-tools.properties").get().asFile
    tempPropsFile.parentFile.mkdirs()

    def props = new Properties()
    if (basePropsFile.asFile.exists()) {
      basePropsFile.asFile.withInputStream { props.load(it) }
    }
    props.setProperty(
        'hibernate.connection.url',
        "jdbc:h2:mem:sakila;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM '\${sqlFile.asFile.absolutePath.replace('\\', '/')}'"
        )

    tempPropsFile.withOutputStream { props.store(it, null) }

    def destDir = outputDir.get().asFile
    destDir.mkdirs()

    ant.taskdef(
        name: 'hibernatetool',
        classname: 'org.hibernate.tool.ant.HibernateToolTask',
        classpath: configurations.hibernateTools.asPath
        )

    ant.hibernatetool(
        destdir: destDir,
        templatepath: templateDir.asFile
        ) {
          jdbcconfiguration(
              propertyfile: tempPropsFile,
              revengfile: revengFile.asFile,
              packagename: "\${project.group}.\${project.name}.generated.entity",
              detectmanytomany: true,
              detectoptimisticlock: true
              )

          hbm2java(jdk5: true, ejb3: true)
        }

    def entityDir = new File(
        destDir,
        "\${project.group}.\${project.name}.generated.entity".replace('.', '/')
        )
    if (entityDir.exists()) {
      entityDir.eachFileMatch(~/.*.java/) { javaFile ->
        def groovyFile = new File(javaFile.parentFile, javaFile.name.replace('.java', '.groovy'))
        javaFile.renameTo(groovyFile)
        println "Renamed: \${javaFile.name} -> \${groovyFile.name}"
      }
    }
  }
}
// highlight-added-end

sourceSets {
  main {
    // ...
// highlight-added-start
    groovy {
      srcDir(layout.buildDirectory.dir("generated/sources/hibernate"))
    }
// highlight-added-end
  }
}
// ...
// highlight-added-start
tasks.named('compileGroovy') {
  dependsOn 'generateEntities'
}
// highlight-added-end`}
  </CollapsibleCodeBlock>
);

export const BuildGradle = () => (
  <Tabs groupId="language" queryString>
    <TabItem value="java" label="Java" default>
      <BuildGradleJava />
    </TabItem>
    <TabItem value="kotlin" label="Kotlin">
      <BuildGradleKt />
    </TabItem>
    <TabItem value="groovy" label="Groovy">
      <BuildGradleGroovy />
    </TabItem>
  </Tabs>
);
